### ISSUE TITLE
Reporte

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-uzias10#2]
[Reporte de Libreria.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-uzias10/files/6340973/Reporte.de.Libreria.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20

Calificó: Antonio González

**Comment by josealfredo79** [comment]
esta bien hecho y revisado.
